### PR TITLE
Editor support

### PR DESCRIPTION
**Pull request by andyboeh**
This adds initial support for an editor component. I did quite some changes to your code:
- Switched to DoukWiki's minimizer for JS and CSS
- Removed now obsolete action/viewer.php
- Added default diagram if the content is empty

The editor works similarly to "edittable": You get a sall "Edit" icon beneath the diagram and, once you click it, you can edit just this diagram. The formatted, changed XML saved back to the Wiki page.

What's missing, but would be nice, is a tool bar button that adds this default content.

### CODE REVIEW

**Comment by andyboeh** [comment]
I had to partially revert action/viewer.php as DokuWiki's minifier can't minify the original bpmnio version properly. I also updated it to v0.15.1

**Comment by jdehaan** [comment]
Thanks for the contribution. I've been on vacation a couple of weeks and now I have a quite high stack of tasks to get rid of. As the code is used in production I need to carefully review and check the code. Please be patient. Best regards.

**Comment by juliusstoerrle** [comment]
As an administrator I would like to disable editing either page wide and/or overwrite the global setting with an attribute on the <bpmnio> tag. Having the editor enabled will probably result in different versions of processes in my organization. 

(Otherwise I like that an editor is there if you need it)

**Comment by jdehaan** [comment]
Thanks for the comment! I plan to add the editor alike the table editor for example. The plugin would not bypass normal page rules, that means people without write rights won't be able to change things. But you are right, if the editor is too easily accessible someone might inadvertently modify things. Maybe adding an optional flag like `read-only` to the options will mute the editor. I think that is a good idea.

**Comment by ghost** [comment]
Wow, this sounds fantastic! I would love to see this merged into the main branch. Is this still being actioned?

**Comment by jdehaan** [comment]
The current state needs to be adapted to the current master to get mergeable. As our flow involves using an external editor and are only interested in the viewer I do not have much time to make this fit test and maintain it. I definitively would merge a clean patch if it is implemented as opt-in.

**Comment by jdehaan** [comment]
Closing as obsoleted by #32

**Pull request closed without merging**
